[AzureCredentials]
APIKey = xxxxxxxxxxxxxxxxxxxxxxx
Endpoint = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Deployment = xxxxxxxxxxxxxxxxxxxxxxxx
version = xxxxxxxxxxxxxxx
EmbeddingDeployment = xxxxxxxxxxxxxxxxxxxxxxxxxxx

[GoogleCred]
key = xxxxxxxxxxxxxxxxxxxxxxxxx
GOOGLE_CSE_ID = xxxxxxxxxxxxxxx
GOOGLE_API_KEY = xxxxxxxxxxxxxxxxxxxxxxx
models = gemini-2.0-flash-001, gemini-2.0-pro-exp-02-05, gemini-2.0-flash-lite-preview-02-05

[Subtitles]
font_dir = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\Ubuntu-Bold.ttf
color = white
x_pos = center
y_pos = center
font_size = 40
stroke_width = 2
font_window = 7

[Logo]
logo = logo.png
height = 150
opacity = .75
x_pos = 850
y_pos = 125

[Prompt]
prompt = The following video is from The Joe rogan poscast.

[remixdirectory]
_dir = ./remix
vid_frame = 60
type = random

[Trimmer]
clipduration = 240
overlap = 30
