[AzureCredentials]
APIKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Endpoint = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Deployment = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
version = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
EmbeddingDeployment = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[GoogleCred]
key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GOOGLE_CSE_ID = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GOOGLE_API_KEY = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[Subtitles]
font_dir = xxxxxxxxxxxxxxxxxxxxxxxxxxxx\Ubuntu-Bold.ttf
color = yellow
x_pos = 40
y_pos = 1400
font_size = 40
stroke_width = 2
font_window = 7

[Logo]
logo = logo90.png
height = 550
opacity = .15
x_pos = center
y_pos = center


[Prompt]
prompt = The following video is from The friends series.


[remixdirectory]
_dir = ./remix
vid_frame = 60
type = None

[Trimmer]
clipduration = 300
overlap = 30