[AzureCredentials]
APIKey = xxxxxxxxxxxxxxxxxxxxxxx
Endpoint =xxxxxxxxxxxxxxxxxxxxxxxxxx
Deployment = xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
version = 2023-05-15
EmbeddingDeployment = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[GoogleCred]
key = xxxxxxxxxxxxxxxxxxxxxxxx
GOOGLE_CSE_ID = xxxxxxxxxxxxxxxxxxxxxx
GOOGLE_API_KEY = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[Subtitles]
font_dir = xxxxxxxxxxxxxxxx\Ubuntu-Bold.ttf
color = white
x_pos = center
y_pos = center
font_size = 40
stroke_width = 2
font_window = 7

[Logo]
logo = ./logo.png
height = 150
opacity = .75
x_pos = 850
y_pos = 125

[Prompt]
prompt = please generate Youtube shorts video or list of shorts videos only in case when video contain multiple interesting topics , from provided video content where each video duration should be between 50 seconds to 1 minutes 20 seconds only,for one video try to make as less cuts as possible while making sure not including unecessary parts and also that short video should be interesting and every subclib should be in continuation of same topic,avoid abrupt transitions or fragmented storytelling. remember each video duration should be between 50 seconds to 1 minutes 20 seconds only,Here is the video clip content : `{all_segments}`


[remixdirectory]
_dir = ./remix
vid_frame = 60
type = random